### ISSUE TITLE
Create the Folder before Creating the file

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/backend#10]
File = "projects/add_project.php"

Instead of creating a new file alone, We should create a new folder and then create the file inside the folder.

Aim: This will help us create a system render of files and other folders inside that particular project for the end-user.

We can call the file "index.html" and maintain the project_location name(_code line 22_)  for the folder, In order to make every folder very unique. (Remember that folders do not have an extension)

**Comment by royninja** [comment]
do I need to create a folder named add_project and the php willbe inside add_project folder?

**Comment by NtemKenyor** [comment]
> do I need to create a folder named add_project and the php willbe inside add_project folder?

No. I'm trying to direct you to where you will be contributing to for this issue. All additions should be in that file "add_project.php". Do you understand?

**Comment by NtemKenyor** [comment]
For more details:

You should only be adjusting the following code lines
line 22
line 50 to 55

GOAL:
The goal is to create a folder for any particular project sent to that endpoint and create a file inside of the folder called "index.html"

**Comment by royninja** [comment]
yes, its clear, let me connect you with a solution.
Thank you for  the clarification

**Comment by NtemKenyor** [comment]
I will be closing this issue for some discussion as the request pull request has somehow addressed this.
