### ISSUE TITLE
adjust line 50 of get_elements.php

### ISSUE THREAD

**Issue by NtemKenyor** [KwickerHub/backend#4]
Some variables in line 50 are not defined. Your Job is simple: Just remove the undefined variables and make sure that the content the array is sending out are the parameters in the query.

**Comment by dangenendt** [comment]
I can do this! ☝️
Can you assign me?

**Comment by NtemKenyor** [comment]
yea sure. No problem

**Comment by NtemKenyor** [comment]
@dangenendt the Job has been assigned to you. Sorry for the delay

**Comment by dangenendt** [comment]
No problem. Thank you!
Will do it!

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
